steps:
- id: build-builder
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ( docker pull gcr.io/$PROJECT_ID/$REPO_NAME:builder-$BRANCH_NAME || true )
    && docker build --target builder -t gcr.io/$PROJECT_ID/$REPO_NAME:builder-$BRANCH_NAME --cache-from gcr.io/$PROJECT_ID/$REPO_NAME:builder-$BRANCH_NAME .
- id: build-base
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ( docker pull gcr.io/$PROJECT_ID/$REPO_NAME:base-$BRANCH_NAME || true )
    && docker build --target base -t gcr.io/$PROJECT_ID/$REPO_NAME:base-$BRANCH_NAME --cache-from gcr.io/$PROJECT_ID/$REPO_NAME:base-$BRANCH_NAME .
- id: build-image
  waitFor: ['build-builder', 'build-base']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:&COMMIT_SHAE', '.']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker push gcr.io/$PROJECT_ID/$REPO_NAME:builder-$BRANCH_NAME &&
    docker push gcr.io/$PROJECT_ID/$REPO_NAME:base-$BRANCH_NAME
  waitFor:
  - build-image
- name: 'docker/compose'
  args: ['-f', 'docker-compose.ci.yml', '-p', 'parallel_1', 'run', 'test']
  env:
  - 'TEST_IMAGE_NAME=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  waitFor:
  - build-image
- name: 'docker/compose'
  args: ['-f', 'docker-compose.ci.yml', '-p', 'parallel_2', 'run', 'test']
  env:
  - 'TEST_IMAGE_NAME=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  waitFor: 
  - build-image

images: [ 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']