steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
- name: 'docker/compose'
  env:
  - 'TEST_IMAGE_NAME=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  args: ['run', '-f', 'docker-compose.ci.yml', 'test']