version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  test:
    image: gcr.io/docx-cloudbuild-experiment/ci-testbed:${COMMIT_SHA:-latest}
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    command: "bundle exec rails db:setup && bundle exec rspec"
