version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  test:
    build: .
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    command: "bundle exec rails db:setup && bundle exec rspec"
