version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    tmpfs: /var/lib/mysql
  test:
    image: ${TEST_IMAGE_NAME}
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    command: ["/bin/sh", "-c", "bin/wait-for-it -t 0 mysql:3306 && bin/rails db:setup && bin/rspec"]
