default: &default
  adapter: mysql2
  host: <%= ENV.fetch("DATABASE_HOST") { "127.0.0.1" } %>
  port: 3306
  username: root
  password: ''
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ci_testbed_development

test:
  <<: *default
  database: ci_testbed_test
