name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t ci-testbed:latest .
    - name: Test
      run: |
        export TEST_IMAGE_NAME=ci-testbed:latest
        docker-compose -f docker-compose.ci.yml run test
