name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Cache
      id: docker-image-cache
      uses: actions/cache@v1.1.2
      with:
        path: .docker-cache
        key: docker-image-${{ hashFiles('**/Gemfile.lock Dockerfile') }}
    - name: Build docker image
      run: |
        [ -f .docker-cache/images.tar ] && docker load -i .docker-cache/images.tar
        docker build -t ci-testbed:${{ github.sha }} --cache-from ci-testbed:cache .
        docker tag ci-testbed:${{ github.sha }} ci-testbed:cache
        mkdir -p .docker-cache
        docker save -o. docker-cache/images.tar ci-testbed:cache ruby
    - name: Test
      run: |
        export TEST_IMAGE_NAME=ci-testbed:${{ github.sha }}
        docker-compose -f docker-compose.ci.yml run test
